query Works{
        works {
            id
            name
            section
            createdAt
            updatedAt
            image
            description
        }
}

query Work($id: ID!){
    work(id: $id) {
        id
        name
        section
        createdAt
        updatedAt
        image
        description
    }
}